config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :order_items
  resources :products
  root to: "products#index"
  match '/auth/:provider/callback', to: 'sessions#create', via: :get

  match "/login" => redirect("/auth/twitter"), as: :login, via: :get
  match "/logout" => "sessions#destroy", as: :logout, via: :get


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  #attr_accessible :product_id, :order_id, :quantity
  validates :order_id, presence: true
  validates :product_id, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  belongs_to :order
  belongs_to :product


  def subtotal
    quantity * product.price
    #quantity * product.price
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :load_order, only: [:create]
  before_action :set_order_item, only: [:show, :edit, :destroy]


  # GET /order_items
  # GET /order_items.json
  def index
    @order_items = OrderItem.all
  end

  # GET /order_items/1
  # GET /order_items/1.json
  #def show
  #end

  # GET /order_items/new
  #def new
    #@order_item = OrderItem.new
  #end

  # GET /order_items/1/edit
  def edit
  end

  # POST /order_items
  # POST /order_items.json
  def create
  @order_item = @order.order_items.find_or_initialize_by(product_id: params[:product_id], order_id: @order.id)
  @order_item.quantity += 1 #adds a one to order_item's quantity
  #@order_item = OrderItem.new(product_id: params[:product_id], order_id: @order.id)
  #@order_item = @order.order_items.new(quantity: 1, product_id: params[:product_id])
  respond_to do |format|
    if @order_item.save
      format.html { redirect_to @order, notice: 'Successfully added product to cart.' }
      format.json { render action: 'show', status: :created, location: @order_item }
    else
      format.html { render action: 'new' }
      format.json { render json: @order_item.errors, status: :unprocessable_entity }
    end
  end
end

  # PATCH/PUT /order_items/1
  # PATCH/PUT /order_items/1.json
  def update
    respond_to do |format|
      @order_item = OrderItem.find(params[:id])
      if params[:order_item][:quantity].to_i == 0
        @order_item.destroy
        format.html { redirect_to orders_path, notice: 'Order item was successfully destroyed.'}
      elsif @order_item.update(order_item_params)
        format.html { redirect_to orders_path, notice: 'Order item was successfully updated.'}
        format.json {render :show, status: :ok, location: @order_item }
      else
        format.html { render :edit }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }

      end
    end
  end

  # DELETE /order_items/1
  # DELETE /order_items/1.json
  def destroy
    @order_item.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order item was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = OrderItem.find(params[:id])
    end

  #def load_order
    #begin
      #@order = Order.find(session[:order_id])
    #rescue ActiveRecord::RecordNotFound
      #@order = Order.create(status: "unsubmitted")
      #session[:order_id] = @order.id
    #end
  #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params.require(:order_item).permit(:product_id, :order_id, :quantity)
    end

    def load_order
      @order = Order.find_or_initialize_by(id: session[:order_id], status: "unsubmitted", user_id: session[:user_id])
      if @order.new_record?
      @order.save!
      session[:order_id] = @order.id
    end
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/_form.html.erb
<%= form_for(order_item) do |f| %>
  <% if order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
      <% order_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#<%= f.label :product_id %>
    <%#<%= f.number_field :product_id %>
    <%= @order_item.product.title %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_items/edit.html.erb
<h1>Editing Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

app/views/order_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Items</h1>

<table>
  <thead>
    <tr>
      <th>ProductID</th>
      <th>OrderID</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
    <%#<% for order_item in @order_items %>
      <tr>
        <td><%= order_item.product_id %></td>
        <td><%= order_item.order_id %></td>
        <td><%= order_item.quantity %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Item', new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Back', order_items_path %>

app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ProductID:</strong>
  <%= @order_item.product_id %>
</p>

<p>
  <strong>OrderID:</strong>
  <%= @order_item.order_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_item.quantity %>
</p>
<%= link_to "Empty Cart", @order, data: { confirm: 'Are you sure?' }, method: :delete %>
<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>